name: NearMissValueResolverException
class_comment: '# * Lets value resolvers tell when an argument could be under their
  watch but failed to be resolved.

  # *

  # * Throwing this exception inside `ValueResolverInterface::resolve` does not interrupt
  the value resolvers chain.'
dependencies: []
properties: []
methods: []
traits: []
interfaces: []
